image: Visual Studio 2017

platform: Any CPU
configuration: Release

before_build:
 - nuget restore "src/backend/Shared/EventBus/EventBus.sln"
build:
 verbosity: quiet
 project: src/backend/Shared/EventBus/EventBus.sln